### ISSUE TITLE
Add some more labels

### ISSUE THREAD

**Issue by regexident** [xavierchow/github-label-template#3]
The current set of labels is a great improvement over GitHub's default set of labels.
But there is still some room for improvement, I think.

As such I'd like to propose the addition of the following:

### Status:

```
Status: Help Wanted [yellow]
```

### Effort:

```
Effort: Easy [green]
Effort: Mentored [yellow]
Effort: Medium [orange]
Effort: Hard [red]
```

### Type:

```
Type: Tracking Issue [?]
Type: Enhancement [?]
Type: Cleanup [?]
```

What do you think?

**Comment by xavierchow** [comment]
The labels of this repo are just as a template/reference, you can customize your own by editing the exported JSON file.
However, I have no objection to enhancing this repo's label sets, feel free to send a PR.

**Comment by regexident** [comment]
I ended up making my own [set of labels](https://github.com/regexident/github-labels) with fine-tuned colors. 😇
