### ISSUE TITLE
Add support for issue description

### ISSUE THREAD

**Issue by itsdevdom** [xavierchow/github-label-template#4]
Some time ago, GitHub added the feature that one can (optionally!) define a description for labels. As of now, it seems that this tool is not able to handle this new property, it will just ignore it. It would be very nice to see this tool being able to manage issue description as well!

**Comment by itsdevdom** [comment]
It it's fine with you, I would be willing to create a PR for this feature! Just let me know :)

**Comment by xavierchow** [comment]
@dominique-mueller sorry for the late response, feel free to send a PR for it!
